### ISSUE TITLE
Create a system property endpoint does not support CORS

### ISSUE THREAD

**Issue by bernard-ng** [igniterealtime/openfire-restAPI-plugin#61] opened 2021-07-09 13:20 UTC
It seems to me that the endpoint of creation of a system property does not take into account the CORS, where the edition and the listing of all the properties support it

Access to XMLHttpRequest at 'http://localhost:9090/plugins/restapi/v1/system/properties' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I am creating a client with angular (typescript) 
```ts
// CORS supported
getSystemProperty(key: string): Observable<SystemProperty> {
  return this.http.get<SystemProperty>(`${this.baseUrl}/system/properties/${key}`);
}

// CORS not supported
createSystemProperty(data: SystemProperty): Observable<SystemProperty> {
  return this.http.post<SystemProperty>(`${this.baseUrl}/system/properties`, data);
}
```

I guess CORS is not supported because any response is returned 

https://github.com/igniterealtime/openfire-restAPI-plugin/blob/76d554390f56e7911bae57a362c09e2e52fc5b76/src/java/org/jivesoftware/openfire/plugin/rest/RESTServicePlugin.java#L160-L167

How can fix this ?

**Comment by Fishbowler** [comment] 2022-04-11 14:45
Unsure if the question predates the code, but I'd expect the CORSFilter to handle this automatically for every request.

https://github.com/igniterealtime/openfire-restAPI-plugin/blob/dfaa49ffa928ee641aca636c2911dcd9be722468/src/java/org/jivesoftware/openfire/plugin/rest/CORSFilter.java#L33-L38

Clearly the question has been unanswered for a good while, but did you work around this problem?

**Comment by Fishbowler** [comment] 2022-06-24 15:09
I can't reproduce this 1.8.1 - I'm gonna close it for now. Feel free to reopen it if you spot it again.

**Closed by Fishbowler** 2022-06-24 15:09 UTC
